Neos:
  Neos:
    Ui:
      resources:
        stylesheets:
          Unikka.LoginAs:LoginAsUserMenu:
            resource: resource://Unikka.LoginAs/Public/LoginAsUserMenu/Plugin.css
        javascript:
          Unikka.LoginAs:LoginAsUserMenu:
            resource: resource://Unikka.LoginAs/Public/LoginAsUserMenu/Plugin.js
    userInterface:
      translation:
        autoInclude:
          'Unikka.LoginAs':
          - 'Main'
  Flow:
    mvc:
      routes:
        'Unikka.LoginAs': true
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Unikka.LoginAs:Controllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Unikka\LoginAs\Controller\.*'
